data = T{
	items = {
		tinnin = {
			t1 = {
				['Vulpangue'] = {'Hellcage Butterfly', 'Vulpangue\'s Wing', false, false,},
				['Chamrosh'] = {'Floral Nectar', 'Chamrosh\'s Beak', false, false,},
				['Cheese Hoarder Gigiroon'] = {'Rodent Cheese', 'Gigiroon\'s Cape', false, false,},
			},
			t2 = {
				['Iriz Ima'] = {'Senorita Pamama', 'Iriz Ima\'s Hide', false, false,},
				['Lividroot Amooshah'] = {'Oily Blood', 'Amoosh.\'s Tendril', false, false,},
				['Iriri Samariri'] = {'Samariri Corpsehair', 'Iriri Samariri\'s Hat', false, false,},
			},
			t3 = {
				['Armed Gears'] = {'Ferrite', 'A. Gears\' Fragment', false, false,},
				['Gotoh Zha the Redolent'] = {'Sheep Botfly', 'G. Zha\'s Necklace', false, false,},
				['Dea'] = {'Olzhiryan Cactus', 'Dea\'s Horn', false, false,},
			},
			t4 = {
				['Tinnin'] = {'Monkey Wine', 'Tinnin\'s Fang', false, false,},
			},
		},
		sarameya = {
			t1 = {
				['Brass Borer'] = {'Shadeleaf','B. Borer\'s Cocoon', false, false,},
				['Claret'] = {'Pectin','Claret Globule', false, false,},
				['Ob'] = {'Cog Lubricant','Ob\'s Arm', false, false,},
			},
			t2 = {
				['Anantaboga'] = {'Raw Buffalo','Anantaboga\'s Heart', false, false,},
				['Dextrose'] = {'Granulated Sugar','Dextrose\'s Blubber', false, false,},
				['Reacton'] = {'Bone Charcoal','Reacton\'s Ashes', false, false,},
			},
			t3 = {
				['Achamoth'] = {'Rock Juice','Acham.\'s Antenna', false, false,},
				['Khromasoul Bhurborlor'] = {'Vinegar Pie','Bblr.\'s Vambrace', false, false,},
				['Nosferatu'] = {'Pure Blood','Nosferatu\'s Claw', false, false,},
			},
			t4 = {
				['Sarameya'] = {'Buffalo Corpse','Sarameya\'s Hide', false, false,},
			},
		},
		tyger = {
			t1 = {
				['Velionis'] = {'Golden Teeth','Velionis\'s Bone', false, false,},
				['Lil\' Apkallu'] = {'Greenling','Lil\' Apkallu\'s Egg', false, false,},
				['Chigre'] = {'Spoilt Blood','Chigre', false, false,},
			},
			t2 = {
				['Verdelet'] = {'Mint Drop','Verdelet\'s Wing', false, false,},
				['Wulgaru'] = {'Opalus Gem','Wulgaru\'s Head', false, false,},
				['Zareehkl the Jubilant'] = {'M. No. 11 Molting','Zrkl.\'s Neckpiece', false, false,},
			},
			t3 = {
				['Experimental Lamia'] = {'Myrrh','Ex. Lamia Armband', false, false,},
				['Mahjlaef the Paintorn'] = {'Exorcism Treatise','Mahjlaef\'s Staff', false, false,},
				['Nuhn'] = {'Rose Scampi','Nuhn\'s Esca', false, false,},
			},
			t4 = {
				['Tyger'] = {'Singed Buffalo','Tyger\'s Tail', false, false,},
			},
		},
		pw = {
			['Pandemonium Warden'] = {'Pandemonium Key', false},
		},
	},
	keyitems = T{
		['Maroon Seal'] = 998,
		['Apple Green Seal'] = 999,
		['Charcoal Grey Seal'] = 1000,
		['Deep Purple Seal'] = 1001,
		['Chestnut-colored Seal'] = 1002,
		['Lilac-colored Seal'] = 1003,
		['Cerise Seal'] = 1004,
		['Salmon-colored Seal'] = 1005,
		['Copper-colored Seal'] = 1008,
		['Gold-colored Seal'] = 1007,
		['Purplish Grey Seal'] = 1006,
		['Bright Blue Seal'] = 1009,
		['Pine Green Seal'] = 1010,
		['Amber-colored Seal'] = 1011,
		['Taupe-colored Seal'] = 1013,
		['Fallow-colored Seal'] = 1012,
		['Sienna-colored Seal'] = 1014,
		['Lavender-colored Seal'] = 1015,
		['Sicklemoon salt'] = 1016,
		['Silver Sea salt'] = 1017,
		['Cyan Deep salt'] = 1018,
	},
	tradeitems = T{
		[16986605] = 'Hellcage Butterfly',
		[17043917] = 'Floral Nectar',
		[17072279] = 'Rodent Cheese',
		[16986606] = 'Senorita Pamama',
		[16990563] = 'Oily Blood',
		[17043918] = 'Samariri Corpsehair',
		[17072280] = 'Ferrite',
		[16986607] = 'Sheep Botfly',
		[16990564] = 'Olzhiryan Cactus',
		[16986608] = 'Monkey Wine',
		[17027515] = 'Shadeleaf',
		[17027516] = 'Pectin',
		[17072278] = 'Cog Lubricant',
		[17027517] = 'Raw Buffalo',
		[17031609] = 'Granulated Sugar',
		[17031610] = 'Bone Charcoal',
		[17031611] = 'Rock Juice',
		[17027518] = 'Vinegar Pie',
		[17056369] = 'Pure Blood',
		[17027519] = 'Buffalo Corpse',
		[16998899] = 'Golden Teeth',
		[16998898] = 'Greenling',
		[17056372] = 'Spoilt Blood',
		[17101256] = 'Mint Drop',
		[17072281] = 'Opalus Gem',
		[16998900] = 'Merrow No. 11 Molting',
		[17101257] = 'Myrrh',
		[17101258] = 'Exorcism Treatise',
		[16998901] = 'Rose Scampi',
		[17101259] = 'Singed Buffalo',
		[17056370] = 'Pandemonium Key',
		--sneaking in ADL trade items
		[17330781] = 'Odious Skull',
		[17330782] = 'Odious Horn',
		[17330783] = 'Odious Blood',
		[17330784] = 'Odious Pen',
	},
};

return data;